# Generated by Django 3.0.3 on 2021-07-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gambler',
            name='balance',
        ),
    ]
