# Generated by Django 3.0.3 on 2021-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casino', '0005_auto_20210803_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
